---
title: siomi.net
timezone: Australia/Melbourne
collections:
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
    layout: default
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    title: 
    image: 
    image source name: 
    image source URL: 
- scope:
    path: ''
    type: categories
  values:
    layout: category
    permalink: "/category/:title/"
Author: Stephanie Siomos
Description: 'Hi, I''m Stephanie - a 23-year-old with a Bachelor''s degree in Commerce
  (Finance & Economics) who stumbled into the wild world of financial markets. Welcome. '
url: siomi.net
Avatar URL: "/uploads/stephanie.jpg"
Header Image URL: "/static/header.jpg"
Theme Color: D65545
Twitter URL: https://twitter.com/stephaniesiomos
Instagram URL: https://instagram.com/stephaniesiomos
LinkedIn URL: https://www.linkedin.com/in/stephanie-siomos-b35205b9/
Email Address: stephaniesiomos@gmail.com
paginate: 5
paginate_path: "/blog/page:num/"
permalink: pretty
plugins:
- jekyll-paginate
exclude:
- ".env"
- ".gitignore"
- Rakefile
- Gemfile
- Gemfile.lock
- README.md
- s3_website.yml
